/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface PwcColorPicker {
    'activeColor': string;
    'colors': any;
    'inputValue': string;
  }
}

declare global {


  interface HTMLPwcColorPickerElement extends Components.PwcColorPicker, HTMLStencilElement {}
  var HTMLPwcColorPickerElement: {
    prototype: HTMLPwcColorPickerElement;
    new (): HTMLPwcColorPickerElement;
  };
  interface HTMLElementTagNameMap {
    'pwc-color-picker': HTMLPwcColorPickerElement;
  }
}

declare namespace LocalJSX {
  interface PwcColorPicker {
    'activeColor'?: string;
    'colors'?: any;
    'inputValue'?: string;
    'onColorPickedEvent'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'pwc-color-picker': PwcColorPicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'pwc-color-picker': LocalJSX.PwcColorPicker & JSXBase.HTMLAttributes<HTMLPwcColorPickerElement>;
    }
  }
}


