/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface ColorPicker {
    'colors': any;
  }
}

declare global {


  interface HTMLColorPickerElement extends Components.ColorPicker, HTMLStencilElement {}
  var HTMLColorPickerElement: {
    prototype: HTMLColorPickerElement;
    new (): HTMLColorPickerElement;
  };
  interface HTMLElementTagNameMap {
    'color-picker': HTMLColorPickerElement;
  }
}

declare namespace LocalJSX {
  interface ColorPicker {
    'colors'?: any;
    'onColorPickedEvent'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'color-picker': ColorPicker;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'color-picker': LocalJSX.ColorPicker & JSXBase.HTMLAttributes<HTMLColorPickerElement>;
    }
  }
}


